alias sudo='sudo -E'
alias vim='nvim'
alias ovim='vim'
alias jenv='pyenv global anaconda3-5.3.1'
alias senv='pyenv global system'
alias jt='jupyter-notebook &'
alias qvim='nvim-qt --geometry 1024x640 --nofork'
