#!/bin/bash
if [ -f /proc/sys/fs/binfmt_misc/WSLInterop ] || [ "${OS}" == "Windows_NT" ]; then
  /mnt/c/Program\ Files/AutoHotKey/AutoHotkeyU64.exe "C:\tools\AutoHotKey\ImDisable.ahk"
else
  fcitx-remote -c
fi
