[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'raphamorim/lucario'
hook_add = '''
  colorscheme lucario
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/anzu.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'molokai'
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  source ~/.config/nvim/plugins/tagbar.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_vert_resize = 1
  let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
  let g:sonictemplate_vim_template_dir = ['~/.config/nvim/template']
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/.cheatsheet.md'
'''

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
  map R <Plug>(operator-replace) 
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''
[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'skywind3000/vim-quickui'
hook_add = '''
  source ~/.config/nvim/plugins/quickui.vim
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
hook_add = '''
  lua require("scrollbar").setup()
'''

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = '''
  lua require("toggleterm").setup()
'''
