[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['python', 'golang', 'c', 'cpp', 'rust']
build = './install_gadget.py --enable-c --enable-python --enable-go --force-enable-rust'
hook_add = '''
  source ~/.config/nvim/plugins/vimspector.vim
'''
