[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''
hook_source = '''
  source ~/.config/nvim/plugins/deoplete_post.vim
'''
on_i=1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i=1
hook_source = '''
  source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  source ~/.config/nvim/plugins/go.vim
'''
