[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''
hook_source = '''
  source ~/.config/nvim/plugins/deoplete_post.vim
'''
on_i=1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i=1
hook_source = '''
  source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['python', 'golang', 'c', 'cpp', 'rust']
build = './install_gadget.py --enable-c --enable-python --enable-go --force-enable-rust'
hook_add = '''
  source ~/.config/nvim/plugins/vimspector.vim
'''
