[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''
hook_source = '''
  source ~/.config/nvim/plugins/deoplete_post.vim
'''
on_i=1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i=1
hook_source = '''
  source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_source = '''
    let g:deoplete#sources#clang#libclang_path = system("llvm-config --prefix")[:-2] . '/l
ib/libclang.dylib'
    let g:deoplete#sources#clang#clang_header = system("llvm-config --prefix")[:-2] . '/lib/clang'
    let g:deoplete#sources#clang#sort_algo = 'priority'
    let g:deoplete#sources#clang#clang_complete_database="./build/"
'''
depends = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  source ~/.config/nvim/plugins/go.vim
'''
